### ISSUE TITLE
Configuration check fails

### ISSUE THREAD

**Issue by gettingerr** [romedtino/simple-wyze-vac#29]
I followed installation instructions but after adding my wyze credentials (I don't use 2FA), home assistant fails config validation with error:  Integration error: simple_wyze_vac - Requirements for simple_wyze_vac not found: ['https://github.com/romedtino/wyze-sdk/archive/refs/tags/10.2.7.zip#wyze-sdk==10.2.7'].

**Comment by romedtino** [comment]
Are you using 1.7beta3? There's an annoying dependency issue on Home Assistant when it comes to dependencies of a custom component. Are you running on a Docker container? Are you coming from a previous install? What I usually have to do is

- Uninstall custom component (Simple Wyze Vac) through HACS
- Restart Home Assistant
- (Sometimes even good to reboot the whole box Home Assistant is running on as this doesn't always clear the cache)
- Reinstall 

If it is still having trouble can you share detail on how you setup your Home Assistant instance because HA should automatically just pull that dependency 🤔

**Comment by gettingerr** [comment]
Hello!

I am now on the 1.7beta3 but it was an issue previously on the non beta
version. I am running in a Docker container, fresh install. I am running on
an unraid server with Home Assistant from the Community Apps store. Using
the steps you outlined have got me past the configuration check issues,
though now I still do not see any vacuum entities. If I try to install the
simple wyze vac integration I get the following error message:

**Comment by gettingerr** [comment]
[31m2022-05-03 22:39:47 ERROR (SyncWorker_1) [homeassistant.util.package]
Unable to install package
https://github.com/romedtino/wyze-sdk/archive/refs/tags/10.2.7.zip#wyze-sdk==10.2.7:
ERROR: Error [Errno 2] No such file or directory: 'git' while executing
command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your
PATH? [0m
[31m2022-05-03 22:39:47 ERROR (MainThread) [aiohttp.server] Error handling
request

**Comment by romedtino** [comment]
Ah, I highly recommend installing git though I'm surprised pip just doesn't try to unzip the archive...

I've gone ahead and put out another version (1.7beta4) with the requirements point directly to the zip as opposed to having the VCS style URL. Do you mind giving that a try when you get the chance?

**Comment by romedtino** [comment]
I tried getting rid of the explicit package name and version number here but HA seems to require it. I think you're going to need to install git in the container you're running Home Assistant on. A bit surprised it's not installed and I think that's the safer bet because other components could also rely on the git method of installing python dependencies.

**Comment by gettingerr** [comment]
Still fails on beta4. Unfortunately I am not good enough at all this to
figure out how to install git on my home assistant container. Tried
googling but cannot figure it out. Thanks for the help!

  [31m2022-05-08 20:43:52 ERROR (SyncWorker_2) [homeassistant.util.package]
Unable to install package
https://github.com/romedtino/wyze-sdk/archive/refs/tags/10.2.7.zip#wyze-sdk==10.2.7:
ERROR: Error [Errno 2] No such file or directory: 'git' while executing
command git version

ERROR: Cannot find command 'git' - do you have 'git' installed and in your
PATH? [0m
[31m2022-05-08 20:43:52 ERROR (MainThread) [aiohttp.server] Error handling
request
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435,
in _handle_request
resp = await request_handler(request)
File "/usr/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in
_handle
resp = await handler(request)
File "/usr/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line
117, in impl
return await handler(request)
File
"/usr/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py",
line 60, in security_filter_middleware
return await handler(request)
File
"/usr/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py",
line 222, in forwarded_middleware
return await handler(request)
File
"/usr/lib/python3.9/site-packages/homeassistant/components/http/request_context.py",
line 28, in request_context_middleware
return await handler(request)
File
"/usr/lib/python3.9/site-packages/homeassistant/components/http/ban.py",
line 79, in ban_middleware
return await handler(request)
File
"/usr/lib/python3.9/site-packages/homeassistant/components/http/auth.py",
line 219, in auth_middleware
return await handler(request)
File
"/usr/lib/python3.9/site-packages/homeassistant/components/http/view.py",
line 137, in handle
result = await result
File
"/usr/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py",
line 174, in post
return await super().post(request)
File
"/usr/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py",
line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File
"/usr/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py",
line 71, in post
result = await self._flow_mgr.async_init(
File "/usr/lib/python3.9/site-packages/homeassistant/data_entry_flow.py",
line 205, in async_init
flow, result = await task
File "/usr/lib/python3.9/site-packages/homeassistant/data_entry_flow.py",
line 223, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/lib/python3.9/site-packages/homeassistant/config_entries.py",
line 740, in async_create_flow
await async_process_deps_reqs(self.hass, self._hass_config, integration)
File "/usr/lib/python3.9/site-packages/homeassistant/setup.py", line 360,
in async_process_deps_reqs
await requirements.async_get_integration_with_requirements(
File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line
83, in async_get_integration_with_requirements
await _async_process_integration(hass, integration, done)
File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line
99, in _async_process_integration
await async_process_requirements(
File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line
162, in async_process_requirements
await _async_process_requirements(
File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line
194, in _async_process_requirements
raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for
simple_wyze_vac not found: ['
https://github.com/romedtino/wyze-sdk/archive/refs/tags/10.2.7.zip#wyze-sdk==10.2.7'].
[0m

**Comment by gettingerr** [comment]
Update to the above. I no longer get the git error, just the following:

Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 174, in post
return await super().post(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 71, in post
result = await self._flow_mgr.async_init(
File "/usr/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 205, in async_init
flow, result = await task
File "/usr/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 223, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/lib/python3.9/site-packages/homeassistant/config_entries.py", line 740, in async_create_flow
await async_process_deps_reqs(self.hass, self._hass_config, integration)
File "/usr/lib/python3.9/site-packages/homeassistant/setup.py", line 360, in async_process_deps_reqs
await requirements.async_get_integration_with_requirements(
File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line 83, in async_get_integration_with_requirements
await _async_process_integration(hass, integration, done)
File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line 99, in _async_process_integration
await async_process_requirements(
File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line 162, in async_process_requirements
await _async_process_requirements(
File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line 182, in _async_process_requirements
if pkg_util.is_installed(req):
File "/usr/lib/python3.9/site-packages/homeassistant/util/package.py", line 45, in is_installed
req = pkg_resources.Requirement.parse(urlparse(package).fragment)
File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3147, in parse
req, = parse_requirements(s)
ValueError: not enough values to unpack (expected 1, got 0)[0m

**Comment by romedtino** [comment]
Seems like your Home Assistant instance is having a hard time pulling and setting up python dependencies. I'm not too sure what the issue is but based on that stack trace, it looks pretty deep into Home Assistant itself.

**Comment by hopkinsag1** [comment]
I had the same issue with HA in an Unraid container. After I added git to the Alpine Linux install it worked great.

This is the command:
apk add git

**Comment by gettingerr** [comment]
Thanks for the tip. Fortunately I've since moved my Hass install onto an
odroid (been wanting to do it for a while but raspberry pi prices put me
off). So now I have a little better control over things and have fewer
weird issues like I had with my unRAID container. Feel like my install is
easier to manage now with fewer steps at least. Wyze vac is working great
on the new system! Thanks for all the help and tips and amazing work.

**Comment by romedtino** [comment]
Thanks for the collab, closing this issue 🥳
